-- UniWallet — optional demo data (UIU student, amounts in BDT).
--
-- Import AFTER sql/schema.sql to get a populated account you can log
-- into straight away, which is handy for a demo or a screenshot.
--   email:    demo@uniwallet.test
--   password: demo1234
--
-- Dates are relative to the day you import. Safe to re-run: it clears the
-- demo account first and leaves any real accounts untouched.

USE `uniwallet`;

DELETE FROM `users` WHERE `email` = "demo@uniwallet.test";

INSERT INTO `users` (`full_name`, `email`, `password_hash`) VALUES
  ("Tahmid Rahman", "demo@uniwallet.test", "$2y$12$/xBRhcUiuPkzw04fWwIosuAhUGJvqxzWYWNlBt4MuRUXb.2iFlm1q");
SET @uid = LAST_INSERT_ID();

INSERT INTO `categories` (`user_id`, `name`, `icon`, `is_default`) VALUES
  (@uid, "Tuition & Fees", "🎓", 1),
  (@uid, "Food & Cafeteria", "🍛", 1),
  (@uid, "Transport", "🛺", 1),
  (@uid, "Mobile & Internet", "📱", 1),
  (@uid, "Books & Printing", "📚", 1),
  (@uid, "Rent & Mess", "🏠", 1),
  (@uid, "Hangout & Fun", "🎬", 1),
  (@uid, "Other", "📦", 1);

SET @cat_tuition = (SELECT `category_id` FROM `categories` WHERE `user_id` = @uid AND `name` = "Tuition & Fees");
SET @cat_food = (SELECT `category_id` FROM `categories` WHERE `user_id` = @uid AND `name` = "Food & Cafeteria");
SET @cat_transport = (SELECT `category_id` FROM `categories` WHERE `user_id` = @uid AND `name` = "Transport");
SET @cat_mobile = (SELECT `category_id` FROM `categories` WHERE `user_id` = @uid AND `name` = "Mobile & Internet");
SET @cat_books = (SELECT `category_id` FROM `categories` WHERE `user_id` = @uid AND `name` = "Books & Printing");
SET @cat_rent = (SELECT `category_id` FROM `categories` WHERE `user_id` = @uid AND `name` = "Rent & Mess");
SET @cat_fun = (SELECT `category_id` FROM `categories` WHERE `user_id` = @uid AND `name` = "Hangout & Fun");
SET @cat_other = (SELECT `category_id` FROM `categories` WHERE `user_id` = @uid AND `name` = "Other");

INSERT INTO `expenses` (`user_id`, `category_id`, `amount`, `spent_on`, `note`) VALUES
  (@uid, @cat_other, 300.00, DATE_SUB(CURDATE(), INTERVAL 179 DAY), "gift"),
  (@uid, @cat_food, 135.00, DATE_SUB(CURDATE(), INTERVAL 177 DAY), "canteen lunch"),
  (@uid, @cat_fun, 370.00, DATE_SUB(CURDATE(), INTERVAL 177 DAY), "movie at Bashundhara City"),
  (@uid, @cat_transport, 60.00, DATE_SUB(CURDATE(), INTERVAL 175 DAY), "rickshaw to campus"),
  (@uid, @cat_transport, 35.00, DATE_SUB(CURDATE(), INTERVAL 175 DAY), "Uber home"),
  (@uid, @cat_transport, 105.00, DATE_SUB(CURDATE(), INTERVAL 173 DAY), "rickshaw to campus"),
  (@uid, @cat_transport, 35.00, DATE_SUB(CURDATE(), INTERVAL 172 DAY), "CNG to Badda"),
  (@uid, @cat_food, 170.00, DATE_SUB(CURDATE(), INTERVAL 172 DAY), "biryani with friends"),
  (@uid, @cat_transport, 100.00, DATE_SUB(CURDATE(), INTERVAL 171 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 165.00, DATE_SUB(CURDATE(), INTERVAL 170 DAY), "dinner at mess"),
  (@uid, @cat_food, 135.00, DATE_SUB(CURDATE(), INTERVAL 170 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_food, 70.00, DATE_SUB(CURDATE(), INTERVAL 169 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_mobile, 160.00, DATE_SUB(CURDATE(), INTERVAL 169 DAY), "bKash cash-out fee"),
  (@uid, @cat_food, 145.00, DATE_SUB(CURDATE(), INTERVAL 169 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_books, 280.00, DATE_SUB(CURDATE(), INTERVAL 168 DAY), "project report print"),
  (@uid, @cat_food, 90.00, DATE_SUB(CURDATE(), INTERVAL 168 DAY), "biryani with friends"),
  (@uid, @cat_books, 80.00, DATE_SUB(CURDATE(), INTERVAL 167 DAY), "reference book"),
  (@uid, @cat_transport, 140.00, DATE_SUB(CURDATE(), INTERVAL 167 DAY), "Pathao ride"),
  (@uid, @cat_mobile, 275.00, DATE_SUB(CURDATE(), INTERVAL 167 DAY), "bKash cash-out fee"),
  (@uid, @cat_transport, 125.00, DATE_SUB(CURDATE(), INTERVAL 164 DAY), "Pathao ride"),
  (@uid, @cat_food, 120.00, DATE_SUB(CURDATE(), INTERVAL 164 DAY), "tehari"),
  (@uid, @cat_food, 130.00, DATE_SUB(CURDATE(), INTERVAL 162 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_books, 200.00, DATE_SUB(CURDATE(), INTERVAL 162 DAY), "reference book"),
  (@uid, @cat_transport, 105.00, DATE_SUB(CURDATE(), INTERVAL 162 DAY), "bus fare"),
  (@uid, @cat_books, 75.00, DATE_SUB(CURDATE(), INTERVAL 161 DAY), "photocopy + printing"),
  (@uid, @cat_other, 340.00, DATE_SUB(CURDATE(), INTERVAL 161 DAY), "gift"),
  (@uid, @cat_mobile, 355.00, DATE_SUB(CURDATE(), INTERVAL 159 DAY), "Robi data pack"),
  (@uid, @cat_mobile, 305.00, DATE_SUB(CURDATE(), INTERVAL 159 DAY), "GP internet pack"),
  (@uid, @cat_other, 280.00, DATE_SUB(CURDATE(), INTERVAL 159 DAY), "haircut"),
  (@uid, @cat_food, 65.00, DATE_SUB(CURDATE(), INTERVAL 158 DAY), "biryani with friends"),
  (@uid, @cat_books, 105.00, DATE_SUB(CURDATE(), INTERVAL 158 DAY), "lab manual"),
  (@uid, @cat_food, 170.00, DATE_SUB(CURDATE(), INTERVAL 157 DAY), "tehari"),
  (@uid, @cat_food, 115.00, DATE_SUB(CURDATE(), INTERVAL 157 DAY), "tehari"),
  (@uid, @cat_food, 75.00, DATE_SUB(CURDATE(), INTERVAL 156 DAY), "tehari"),
  (@uid, @cat_fun, 435.00, DATE_SUB(CURDATE(), INTERVAL 156 DAY), "friends' treat"),
  (@uid, @cat_transport, 80.00, DATE_SUB(CURDATE(), INTERVAL 155 DAY), "CNG to Badda"),
  (@uid, @cat_food, 80.00, DATE_SUB(CURDATE(), INTERVAL 154 DAY), "biryani with friends"),
  (@uid, @cat_food, 120.00, DATE_SUB(CURDATE(), INTERVAL 153 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_food, 95.00, DATE_SUB(CURDATE(), INTERVAL 153 DAY), "canteen lunch"),
  (@uid, @cat_food, 130.00, DATE_SUB(CURDATE(), INTERVAL 153 DAY), "cha + singara"),
  (@uid, @cat_transport, 45.00, DATE_SUB(CURDATE(), INTERVAL 152 DAY), "Uber home"),
  (@uid, @cat_other, 435.00, DATE_SUB(CURDATE(), INTERVAL 152 DAY), "gift"),
  (@uid, @cat_rent, 7000.00, DATE_SUB(CURDATE(), INTERVAL 152 DAY), "mess + room rent"),
  (@uid, @cat_fun, 550.00, DATE_SUB(CURDATE(), INTERVAL 151 DAY), "friends' treat"),
  (@uid, @cat_food, 75.00, DATE_SUB(CURDATE(), INTERVAL 151 DAY), "tehari"),
  (@uid, @cat_transport, 55.00, DATE_SUB(CURDATE(), INTERVAL 150 DAY), "rickshaw to campus"),
  (@uid, @cat_other, 325.00, DATE_SUB(CURDATE(), INTERVAL 150 DAY), "haircut"),
  (@uid, @cat_food, 135.00, DATE_SUB(CURDATE(), INTERVAL 150 DAY), "canteen lunch"),
  (@uid, @cat_tuition, 22000.00, DATE_SUB(CURDATE(), INTERVAL 150 DAY), "trimester installment"),
  (@uid, @cat_food, 70.00, DATE_SUB(CURDATE(), INTERVAL 148 DAY), "cha + singara"),
  (@uid, @cat_transport, 40.00, DATE_SUB(CURDATE(), INTERVAL 148 DAY), "CNG to Badda"),
  (@uid, @cat_food, 140.00, DATE_SUB(CURDATE(), INTERVAL 147 DAY), "cha + singara"),
  (@uid, @cat_other, 410.00, DATE_SUB(CURDATE(), INTERVAL 147 DAY), "medicine"),
  (@uid, @cat_food, 170.00, DATE_SUB(CURDATE(), INTERVAL 146 DAY), "tehari"),
  (@uid, @cat_other, 340.00, DATE_SUB(CURDATE(), INTERVAL 146 DAY), "donation"),
  (@uid, @cat_food, 80.00, DATE_SUB(CURDATE(), INTERVAL 145 DAY), "canteen lunch"),
  (@uid, @cat_mobile, 265.00, DATE_SUB(CURDATE(), INTERVAL 145 DAY), "Robi data pack"),
  (@uid, @cat_food, 60.00, DATE_SUB(CURDATE(), INTERVAL 144 DAY), "biryani with friends"),
  (@uid, @cat_other, 370.00, DATE_SUB(CURDATE(), INTERVAL 144 DAY), "medicine"),
  (@uid, @cat_food, 130.00, DATE_SUB(CURDATE(), INTERVAL 144 DAY), "canteen lunch"),
  (@uid, @cat_food, 140.00, DATE_SUB(CURDATE(), INTERVAL 143 DAY), "canteen lunch"),
  (@uid, @cat_transport, 65.00, DATE_SUB(CURDATE(), INTERVAL 143 DAY), "Uber home"),
  (@uid, @cat_fun, 515.00, DATE_SUB(CURDATE(), INTERVAL 142 DAY), "hangout at Dhanmondi"),
  (@uid, @cat_transport, 95.00, DATE_SUB(CURDATE(), INTERVAL 141 DAY), "Pathao ride"),
  (@uid, @cat_transport, 110.00, DATE_SUB(CURDATE(), INTERVAL 141 DAY), "CNG to Badda"),
  (@uid, @cat_books, 155.00, DATE_SUB(CURDATE(), INTERVAL 140 DAY), "lab manual"),
  (@uid, @cat_transport, 125.00, DATE_SUB(CURDATE(), INTERVAL 139 DAY), "rickshaw to campus"),
  (@uid, @cat_other, 245.00, DATE_SUB(CURDATE(), INTERVAL 139 DAY), "donation"),
  (@uid, @cat_food, 135.00, DATE_SUB(CURDATE(), INTERVAL 138 DAY), "cha + singara"),
  (@uid, @cat_books, 220.00, DATE_SUB(CURDATE(), INTERVAL 137 DAY), "reference book"),
  (@uid, @cat_food, 75.00, DATE_SUB(CURDATE(), INTERVAL 137 DAY), "biryani with friends"),
  (@uid, @cat_food, 85.00, DATE_SUB(CURDATE(), INTERVAL 136 DAY), "tehari"),
  (@uid, @cat_transport, 145.00, DATE_SUB(CURDATE(), INTERVAL 136 DAY), "Uber home"),
  (@uid, @cat_fun, 500.00, DATE_SUB(CURDATE(), INTERVAL 134 DAY), "movie at Bashundhara City"),
  (@uid, @cat_books, 100.00, DATE_SUB(CURDATE(), INTERVAL 134 DAY), "project report print"),
  (@uid, @cat_mobile, 375.00, DATE_SUB(CURDATE(), INTERVAL 133 DAY), "GP internet pack"),
  (@uid, @cat_transport, 110.00, DATE_SUB(CURDATE(), INTERVAL 133 DAY), "Pathao ride"),
  (@uid, @cat_food, 150.00, DATE_SUB(CURDATE(), INTERVAL 133 DAY), "tehari"),
  (@uid, @cat_transport, 40.00, DATE_SUB(CURDATE(), INTERVAL 132 DAY), "CNG to Badda"),
  (@uid, @cat_food, 75.00, DATE_SUB(CURDATE(), INTERVAL 132 DAY), "canteen lunch"),
  (@uid, @cat_transport, 90.00, DATE_SUB(CURDATE(), INTERVAL 131 DAY), "CNG to Badda"),
  (@uid, @cat_books, 280.00, DATE_SUB(CURDATE(), INTERVAL 130 DAY), "reference book"),
  (@uid, @cat_food, 130.00, DATE_SUB(CURDATE(), INTERVAL 130 DAY), "biryani with friends"),
  (@uid, @cat_transport, 95.00, DATE_SUB(CURDATE(), INTERVAL 127 DAY), "CNG to Badda"),
  (@uid, @cat_transport, 140.00, DATE_SUB(CURDATE(), INTERVAL 127 DAY), "CNG to Badda"),
  (@uid, @cat_books, 150.00, DATE_SUB(CURDATE(), INTERVAL 127 DAY), "photocopy + printing"),
  (@uid, @cat_food, 125.00, DATE_SUB(CURDATE(), INTERVAL 126 DAY), "biryani with friends"),
  (@uid, @cat_food, 130.00, DATE_SUB(CURDATE(), INTERVAL 125 DAY), "tehari"),
  (@uid, @cat_books, 70.00, DATE_SUB(CURDATE(), INTERVAL 125 DAY), "reference book"),
  (@uid, @cat_transport, 135.00, DATE_SUB(CURDATE(), INTERVAL 124 DAY), "Uber home"),
  (@uid, @cat_transport, 145.00, DATE_SUB(CURDATE(), INTERVAL 124 DAY), "Uber home"),
  (@uid, @cat_transport, 95.00, DATE_SUB(CURDATE(), INTERVAL 123 DAY), "Uber home"),
  (@uid, @cat_rent, 7000.00, DATE_SUB(CURDATE(), INTERVAL 122 DAY), "mess + room rent"),
  (@uid, @cat_books, 40.00, DATE_SUB(CURDATE(), INTERVAL 121 DAY), "lab manual"),
  (@uid, @cat_food, 120.00, DATE_SUB(CURDATE(), INTERVAL 121 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_food, 65.00, DATE_SUB(CURDATE(), INTERVAL 120 DAY), "cha + singara"),
  (@uid, @cat_transport, 95.00, DATE_SUB(CURDATE(), INTERVAL 120 DAY), "Uber home"),
  (@uid, @cat_transport, 130.00, DATE_SUB(CURDATE(), INTERVAL 120 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 85.00, DATE_SUB(CURDATE(), INTERVAL 119 DAY), "cha + singara"),
  (@uid, @cat_food, 70.00, DATE_SUB(CURDATE(), INTERVAL 119 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_transport, 125.00, DATE_SUB(CURDATE(), INTERVAL 118 DAY), "rickshaw to campus"),
  (@uid, @cat_transport, 110.00, DATE_SUB(CURDATE(), INTERVAL 118 DAY), "Uber home"),
  (@uid, @cat_transport, 120.00, DATE_SUB(CURDATE(), INTERVAL 117 DAY), "Pathao ride"),
  (@uid, @cat_transport, 100.00, DATE_SUB(CURDATE(), INTERVAL 117 DAY), "bus fare"),
  (@uid, @cat_other, 455.00, DATE_SUB(CURDATE(), INTERVAL 116 DAY), "medicine"),
  (@uid, @cat_fun, 355.00, DATE_SUB(CURDATE(), INTERVAL 116 DAY), "friends' treat"),
  (@uid, @cat_transport, 80.00, DATE_SUB(CURDATE(), INTERVAL 115 DAY), "bus fare"),
  (@uid, @cat_food, 90.00, DATE_SUB(CURDATE(), INTERVAL 114 DAY), "tehari"),
  (@uid, @cat_transport, 130.00, DATE_SUB(CURDATE(), INTERVAL 112 DAY), "rickshaw to campus"),
  (@uid, @cat_fun, 525.00, DATE_SUB(CURDATE(), INTERVAL 111 DAY), "hangout at Dhanmondi"),
  (@uid, @cat_fun, 630.00, DATE_SUB(CURDATE(), INTERVAL 110 DAY), "hangout at Dhanmondi"),
  (@uid, @cat_other, 305.00, DATE_SUB(CURDATE(), INTERVAL 109 DAY), "donation"),
  (@uid, @cat_food, 145.00, DATE_SUB(CURDATE(), INTERVAL 109 DAY), "biryani with friends"),
  (@uid, @cat_food, 115.00, DATE_SUB(CURDATE(), INTERVAL 109 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_food, 85.00, DATE_SUB(CURDATE(), INTERVAL 108 DAY), "cha + singara"),
  (@uid, @cat_food, 150.00, DATE_SUB(CURDATE(), INTERVAL 108 DAY), "cha + singara"),
  (@uid, @cat_transport, 85.00, DATE_SUB(CURDATE(), INTERVAL 106 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 140.00, DATE_SUB(CURDATE(), INTERVAL 105 DAY), "cha + singara"),
  (@uid, @cat_transport, 40.00, DATE_SUB(CURDATE(), INTERVAL 105 DAY), "rickshaw to campus"),
  (@uid, @cat_other, 155.00, DATE_SUB(CURDATE(), INTERVAL 104 DAY), "gift"),
  (@uid, @cat_food, 175.00, DATE_SUB(CURDATE(), INTERVAL 103 DAY), "biryani with friends"),
  (@uid, @cat_mobile, 345.00, DATE_SUB(CURDATE(), INTERVAL 102 DAY), "bKash cash-out fee"),
  (@uid, @cat_transport, 100.00, DATE_SUB(CURDATE(), INTERVAL 101 DAY), "Uber home"),
  (@uid, @cat_transport, 70.00, DATE_SUB(CURDATE(), INTERVAL 100 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 160.00, DATE_SUB(CURDATE(), INTERVAL 100 DAY), "dinner at mess"),
  (@uid, @cat_transport, 40.00, DATE_SUB(CURDATE(), INTERVAL 99 DAY), "Pathao ride"),
  (@uid, @cat_food, 95.00, DATE_SUB(CURDATE(), INTERVAL 97 DAY), "canteen lunch"),
  (@uid, @cat_transport, 60.00, DATE_SUB(CURDATE(), INTERVAL 97 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 75.00, DATE_SUB(CURDATE(), INTERVAL 97 DAY), "tehari"),
  (@uid, @cat_other, 315.00, DATE_SUB(CURDATE(), INTERVAL 95 DAY), "medicine"),
  (@uid, @cat_food, 125.00, DATE_SUB(CURDATE(), INTERVAL 94 DAY), "dinner at mess"),
  (@uid, @cat_food, 75.00, DATE_SUB(CURDATE(), INTERVAL 94 DAY), "biryani with friends"),
  (@uid, @cat_food, 85.00, DATE_SUB(CURDATE(), INTERVAL 93 DAY), "cha + singara"),
  (@uid, @cat_food, 155.00, DATE_SUB(CURDATE(), INTERVAL 92 DAY), "biryani with friends"),
  (@uid, @cat_food, 125.00, DATE_SUB(CURDATE(), INTERVAL 92 DAY), "dinner at mess"),
  (@uid, @cat_food, 105.00, DATE_SUB(CURDATE(), INTERVAL 92 DAY), "canteen lunch"),
  (@uid, @cat_rent, 7000.00, DATE_SUB(CURDATE(), INTERVAL 92 DAY), "mess + room rent"),
  (@uid, @cat_food, 60.00, DATE_SUB(CURDATE(), INTERVAL 91 DAY), "dinner at mess"),
  (@uid, @cat_transport, 55.00, DATE_SUB(CURDATE(), INTERVAL 90 DAY), "Uber home"),
  (@uid, @cat_transport, 150.00, DATE_SUB(CURDATE(), INTERVAL 90 DAY), "bus fare"),
  (@uid, @cat_books, 260.00, DATE_SUB(CURDATE(), INTERVAL 88 DAY), "project report print"),
  (@uid, @cat_transport, 145.00, DATE_SUB(CURDATE(), INTERVAL 88 DAY), "bus fare"),
  (@uid, @cat_other, 255.00, DATE_SUB(CURDATE(), INTERVAL 88 DAY), "haircut"),
  (@uid, @cat_food, 165.00, DATE_SUB(CURDATE(), INTERVAL 87 DAY), "dinner at mess"),
  (@uid, @cat_transport, 80.00, DATE_SUB(CURDATE(), INTERVAL 86 DAY), "Pathao ride"),
  (@uid, @cat_other, 165.00, DATE_SUB(CURDATE(), INTERVAL 86 DAY), "gift"),
  (@uid, @cat_food, 155.00, DATE_SUB(CURDATE(), INTERVAL 86 DAY), "cha + singara"),
  (@uid, @cat_food, 70.00, DATE_SUB(CURDATE(), INTERVAL 85 DAY), "dinner at mess"),
  (@uid, @cat_books, 300.00, DATE_SUB(CURDATE(), INTERVAL 85 DAY), "reference book"),
  (@uid, @cat_food, 95.00, DATE_SUB(CURDATE(), INTERVAL 84 DAY), "canteen lunch"),
  (@uid, @cat_transport, 50.00, DATE_SUB(CURDATE(), INTERVAL 84 DAY), "Pathao ride"),
  (@uid, @cat_food, 105.00, DATE_SUB(CURDATE(), INTERVAL 83 DAY), "cha + singara"),
  (@uid, @cat_other, 380.00, DATE_SUB(CURDATE(), INTERVAL 83 DAY), "medicine"),
  (@uid, @cat_food, 170.00, DATE_SUB(CURDATE(), INTERVAL 82 DAY), "cha + singara"),
  (@uid, @cat_food, 60.00, DATE_SUB(CURDATE(), INTERVAL 81 DAY), "cha + singara"),
  (@uid, @cat_food, 95.00, DATE_SUB(CURDATE(), INTERVAL 80 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_transport, 60.00, DATE_SUB(CURDATE(), INTERVAL 80 DAY), "Uber home"),
  (@uid, @cat_books, 115.00, DATE_SUB(CURDATE(), INTERVAL 77 DAY), "project report print"),
  (@uid, @cat_food, 60.00, DATE_SUB(CURDATE(), INTERVAL 76 DAY), "cha + singara"),
  (@uid, @cat_food, 90.00, DATE_SUB(CURDATE(), INTERVAL 76 DAY), "canteen lunch"),
  (@uid, @cat_other, 485.00, DATE_SUB(CURDATE(), INTERVAL 75 DAY), "haircut"),
  (@uid, @cat_transport, 120.00, DATE_SUB(CURDATE(), INTERVAL 75 DAY), "Uber home"),
  (@uid, @cat_books, 295.00, DATE_SUB(CURDATE(), INTERVAL 74 DAY), "lab manual"),
  (@uid, @cat_food, 140.00, DATE_SUB(CURDATE(), INTERVAL 74 DAY), "dinner at mess"),
  (@uid, @cat_food, 165.00, DATE_SUB(CURDATE(), INTERVAL 73 DAY), "dinner at mess"),
  (@uid, @cat_transport, 125.00, DATE_SUB(CURDATE(), INTERVAL 72 DAY), "Uber home"),
  (@uid, @cat_food, 125.00, DATE_SUB(CURDATE(), INTERVAL 72 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_books, 50.00, DATE_SUB(CURDATE(), INTERVAL 71 DAY), "lab manual"),
  (@uid, @cat_food, 65.00, DATE_SUB(CURDATE(), INTERVAL 71 DAY), "biryani with friends"),
  (@uid, @cat_food, 75.00, DATE_SUB(CURDATE(), INTERVAL 70 DAY), "tehari"),
  (@uid, @cat_books, 325.00, DATE_SUB(CURDATE(), INTERVAL 70 DAY), "photocopy + printing"),
  (@uid, @cat_transport, 110.00, DATE_SUB(CURDATE(), INTERVAL 70 DAY), "Uber home"),
  (@uid, @cat_food, 95.00, DATE_SUB(CURDATE(), INTERVAL 69 DAY), "canteen lunch"),
  (@uid, @cat_transport, 40.00, DATE_SUB(CURDATE(), INTERVAL 69 DAY), "Uber home"),
  (@uid, @cat_fun, 245.00, DATE_SUB(CURDATE(), INTERVAL 69 DAY), "movie at Bashundhara City"),
  (@uid, @cat_mobile, 260.00, DATE_SUB(CURDATE(), INTERVAL 68 DAY), "GP internet pack"),
  (@uid, @cat_books, 160.00, DATE_SUB(CURDATE(), INTERVAL 68 DAY), "lab manual"),
  (@uid, @cat_food, 145.00, DATE_SUB(CURDATE(), INTERVAL 68 DAY), "tehari"),
  (@uid, @cat_books, 80.00, DATE_SUB(CURDATE(), INTERVAL 67 DAY), "project report print"),
  (@uid, @cat_fun, 445.00, DATE_SUB(CURDATE(), INTERVAL 67 DAY), "movie at Bashundhara City"),
  (@uid, @cat_transport, 55.00, DATE_SUB(CURDATE(), INTERVAL 66 DAY), "rickshaw to campus"),
  (@uid, @cat_transport, 70.00, DATE_SUB(CURDATE(), INTERVAL 66 DAY), "Pathao ride"),
  (@uid, @cat_mobile, 285.00, DATE_SUB(CURDATE(), INTERVAL 65 DAY), "bKash cash-out fee"),
  (@uid, @cat_transport, 30.00, DATE_SUB(CURDATE(), INTERVAL 65 DAY), "bus fare"),
  (@uid, @cat_food, 95.00, DATE_SUB(CURDATE(), INTERVAL 65 DAY), "dinner at mess"),
  (@uid, @cat_food, 120.00, DATE_SUB(CURDATE(), INTERVAL 63 DAY), "cha + singara"),
  (@uid, @cat_mobile, 275.00, DATE_SUB(CURDATE(), INTERVAL 63 DAY), "Robi data pack"),
  (@uid, @cat_transport, 130.00, DATE_SUB(CURDATE(), INTERVAL 63 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 70.00, DATE_SUB(CURDATE(), INTERVAL 62 DAY), "tehari"),
  (@uid, @cat_food, 120.00, DATE_SUB(CURDATE(), INTERVAL 62 DAY), "canteen lunch"),
  (@uid, @cat_rent, 7000.00, DATE_SUB(CURDATE(), INTERVAL 62 DAY), "mess + room rent"),
  (@uid, @cat_other, 330.00, DATE_SUB(CURDATE(), INTERVAL 61 DAY), "medicine"),
  (@uid, @cat_food, 175.00, DATE_SUB(CURDATE(), INTERVAL 61 DAY), "biryani with friends"),
  (@uid, @cat_tuition, 22000.00, DATE_SUB(CURDATE(), INTERVAL 60 DAY), "trimester installment"),
  (@uid, @cat_mobile, 265.00, DATE_SUB(CURDATE(), INTERVAL 59 DAY), "Robi data pack"),
  (@uid, @cat_transport, 110.00, DATE_SUB(CURDATE(), INTERVAL 58 DAY), "Uber home"),
  (@uid, @cat_fun, 525.00, DATE_SUB(CURDATE(), INTERVAL 57 DAY), "hangout at Dhanmondi"),
  (@uid, @cat_fun, 645.00, DATE_SUB(CURDATE(), INTERVAL 56 DAY), "friends' treat"),
  (@uid, @cat_food, 60.00, DATE_SUB(CURDATE(), INTERVAL 56 DAY), "tehari"),
  (@uid, @cat_transport, 70.00, DATE_SUB(CURDATE(), INTERVAL 55 DAY), "CNG to Badda"),
  (@uid, @cat_transport, 80.00, DATE_SUB(CURDATE(), INTERVAL 55 DAY), "Pathao ride"),
  (@uid, @cat_food, 100.00, DATE_SUB(CURDATE(), INTERVAL 55 DAY), "canteen lunch"),
  (@uid, @cat_mobile, 330.00, DATE_SUB(CURDATE(), INTERVAL 54 DAY), "GP internet pack"),
  (@uid, @cat_mobile, 275.00, DATE_SUB(CURDATE(), INTERVAL 53 DAY), "Robi data pack"),
  (@uid, @cat_food, 110.00, DATE_SUB(CURDATE(), INTERVAL 52 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_fun, 430.00, DATE_SUB(CURDATE(), INTERVAL 50 DAY), "movie at Bashundhara City"),
  (@uid, @cat_food, 165.00, DATE_SUB(CURDATE(), INTERVAL 49 DAY), "dinner at mess"),
  (@uid, @cat_transport, 50.00, DATE_SUB(CURDATE(), INTERVAL 48 DAY), "CNG to Badda"),
  (@uid, @cat_transport, 70.00, DATE_SUB(CURDATE(), INTERVAL 47 DAY), "CNG to Badda"),
  (@uid, @cat_books, 260.00, DATE_SUB(CURDATE(), INTERVAL 46 DAY), "photocopy + printing"),
  (@uid, @cat_transport, 140.00, DATE_SUB(CURDATE(), INTERVAL 45 DAY), "Uber home"),
  (@uid, @cat_transport, 120.00, DATE_SUB(CURDATE(), INTERVAL 45 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 155.00, DATE_SUB(CURDATE(), INTERVAL 45 DAY), "tehari"),
  (@uid, @cat_transport, 45.00, DATE_SUB(CURDATE(), INTERVAL 44 DAY), "Pathao ride"),
  (@uid, @cat_transport, 145.00, DATE_SUB(CURDATE(), INTERVAL 44 DAY), "Uber home"),
  (@uid, @cat_food, 115.00, DATE_SUB(CURDATE(), INTERVAL 43 DAY), "cha + singara"),
  (@uid, @cat_food, 155.00, DATE_SUB(CURDATE(), INTERVAL 42 DAY), "dinner at mess"),
  (@uid, @cat_food, 145.00, DATE_SUB(CURDATE(), INTERVAL 41 DAY), "biryani with friends"),
  (@uid, @cat_food, 130.00, DATE_SUB(CURDATE(), INTERVAL 41 DAY), "dinner at mess"),
  (@uid, @cat_food, 80.00, DATE_SUB(CURDATE(), INTERVAL 41 DAY), "dinner at mess"),
  (@uid, @cat_food, 125.00, DATE_SUB(CURDATE(), INTERVAL 40 DAY), "tehari"),
  (@uid, @cat_food, 175.00, DATE_SUB(CURDATE(), INTERVAL 39 DAY), "cha + singara"),
  (@uid, @cat_other, 330.00, DATE_SUB(CURDATE(), INTERVAL 39 DAY), "donation"),
  (@uid, @cat_transport, 60.00, DATE_SUB(CURDATE(), INTERVAL 38 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 70.00, DATE_SUB(CURDATE(), INTERVAL 37 DAY), "cha + singara"),
  (@uid, @cat_food, 165.00, DATE_SUB(CURDATE(), INTERVAL 36 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_fun, 570.00, DATE_SUB(CURDATE(), INTERVAL 35 DAY), "friends' treat"),
  (@uid, @cat_mobile, 235.00, DATE_SUB(CURDATE(), INTERVAL 34 DAY), "Robi data pack"),
  (@uid, @cat_food, 155.00, DATE_SUB(CURDATE(), INTERVAL 34 DAY), "canteen lunch"),
  (@uid, @cat_food, 105.00, DATE_SUB(CURDATE(), INTERVAL 33 DAY), "biryani with friends"),
  (@uid, @cat_transport, 95.00, DATE_SUB(CURDATE(), INTERVAL 33 DAY), "CNG to Badda"),
  (@uid, @cat_rent, 7000.00, DATE_SUB(CURDATE(), INTERVAL 32 DAY), "mess + room rent"),
  (@uid, @cat_fun, 545.00, DATE_SUB(CURDATE(), INTERVAL 31 DAY), "friends' treat"),
  (@uid, @cat_transport, 70.00, DATE_SUB(CURDATE(), INTERVAL 30 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 115.00, DATE_SUB(CURDATE(), INTERVAL 30 DAY), "dinner at mess"),
  (@uid, @cat_books, 280.00, DATE_SUB(CURDATE(), INTERVAL 30 DAY), "project report print"),
  (@uid, @cat_fun, 690.00, DATE_SUB(CURDATE(), INTERVAL 27 DAY), "friends' treat"),
  (@uid, @cat_other, 225.00, DATE_SUB(CURDATE(), INTERVAL 27 DAY), "gift"),
  (@uid, @cat_food, 125.00, DATE_SUB(CURDATE(), INTERVAL 26 DAY), "dinner at mess"),
  (@uid, @cat_mobile, 365.00, DATE_SUB(CURDATE(), INTERVAL 24 DAY), "GP internet pack"),
  (@uid, @cat_transport, 35.00, DATE_SUB(CURDATE(), INTERVAL 24 DAY), "rickshaw to campus"),
  (@uid, @cat_books, 160.00, DATE_SUB(CURDATE(), INTERVAL 24 DAY), "photocopy + printing"),
  (@uid, @cat_mobile, 195.00, DATE_SUB(CURDATE(), INTERVAL 23 DAY), "bKash cash-out fee"),
  (@uid, @cat_food, 140.00, DATE_SUB(CURDATE(), INTERVAL 23 DAY), "tehari"),
  (@uid, @cat_transport, 45.00, DATE_SUB(CURDATE(), INTERVAL 23 DAY), "rickshaw to campus"),
  (@uid, @cat_transport, 105.00, DATE_SUB(CURDATE(), INTERVAL 21 DAY), "CNG to Badda"),
  (@uid, @cat_food, 160.00, DATE_SUB(CURDATE(), INTERVAL 20 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_food, 130.00, DATE_SUB(CURDATE(), INTERVAL 20 DAY), "cha + singara"),
  (@uid, @cat_food, 100.00, DATE_SUB(CURDATE(), INTERVAL 19 DAY), "dinner at mess"),
  (@uid, @cat_books, 165.00, DATE_SUB(CURDATE(), INTERVAL 19 DAY), "project report print"),
  (@uid, @cat_food, 90.00, DATE_SUB(CURDATE(), INTERVAL 18 DAY), "canteen lunch"),
  (@uid, @cat_other, 460.00, DATE_SUB(CURDATE(), INTERVAL 18 DAY), "medicine"),
  (@uid, @cat_transport, 115.00, DATE_SUB(CURDATE(), INTERVAL 15 DAY), "bus fare"),
  (@uid, @cat_food, 115.00, DATE_SUB(CURDATE(), INTERVAL 13 DAY), "cha + singara"),
  (@uid, @cat_transport, 120.00, DATE_SUB(CURDATE(), INTERVAL 12 DAY), "Pathao ride"),
  (@uid, @cat_transport, 115.00, DATE_SUB(CURDATE(), INTERVAL 11 DAY), "bus fare"),
  (@uid, @cat_food, 160.00, DATE_SUB(CURDATE(), INTERVAL 11 DAY), "cha + singara"),
  (@uid, @cat_mobile, 385.00, DATE_SUB(CURDATE(), INTERVAL 11 DAY), "GP internet pack"),
  (@uid, @cat_transport, 55.00, DATE_SUB(CURDATE(), INTERVAL 10 DAY), "Pathao ride"),
  (@uid, @cat_food, 90.00, DATE_SUB(CURDATE(), INTERVAL 9 DAY), "cha + singara"),
  (@uid, @cat_food, 140.00, DATE_SUB(CURDATE(), INTERVAL 8 DAY), "tehari"),
  (@uid, @cat_food, 90.00, DATE_SUB(CURDATE(), INTERVAL 7 DAY), "tehari"),
  (@uid, @cat_transport, 115.00, DATE_SUB(CURDATE(), INTERVAL 7 DAY), "rickshaw to campus"),
  (@uid, @cat_food, 110.00, DATE_SUB(CURDATE(), INTERVAL 6 DAY), "canteen lunch"),
  (@uid, @cat_food, 135.00, DATE_SUB(CURDATE(), INTERVAL 6 DAY), "biryani with friends"),
  (@uid, @cat_food, 65.00, DATE_SUB(CURDATE(), INTERVAL 5 DAY), "biryani with friends"),
  (@uid, @cat_food, 175.00, DATE_SUB(CURDATE(), INTERVAL 5 DAY), "dinner at mess"),
  (@uid, @cat_mobile, 170.00, DATE_SUB(CURDATE(), INTERVAL 4 DAY), "GP internet pack"),
  (@uid, @cat_food, 145.00, DATE_SUB(CURDATE(), INTERVAL 3 DAY), "Fuska at Bashundhara gate"),
  (@uid, @cat_transport, 70.00, DATE_SUB(CURDATE(), INTERVAL 2 DAY), "bus fare"),
  (@uid, @cat_books, 210.00, DATE_SUB(CURDATE(), INTERVAL 2 DAY), "project report print"),
  (@uid, @cat_food, 60.00, DATE_SUB(CURDATE(), INTERVAL 2 DAY), "canteen lunch"),
  (@uid, @cat_rent, 7000.00, DATE_SUB(CURDATE(), INTERVAL 2 DAY), "mess + room rent"),
  (@uid, @cat_food, 115.00, DATE_SUB(CURDATE(), INTERVAL 1 DAY), "canteen lunch"),
  (@uid, @cat_other, 205.00, DATE_SUB(CURDATE(), INTERVAL 0 DAY), "donation"),
  (@uid, @cat_food, 165.00, DATE_SUB(CURDATE(), INTERVAL 0 DAY), "cha + singara");

-- Extra entries so the current month always looks lived-in: the 1st of the
-- month (rent, data pack, trimester installment) plus the last two days.
SET @first = DATE_FORMAT(CURDATE(), "%Y-%m-01");
INSERT INTO `expenses` (`user_id`, `category_id`, `amount`, `spent_on`, `note`) VALUES
  (@uid, @cat_rent,      7000.00, @first, "mess + room rent"),
  (@uid, @cat_tuition,   2500.00, @first, "lab fee installment"),
  (@uid, @cat_mobile,     399.00, @first, "Robi 30-day data pack"),
  (@uid, @cat_food,       220.00, @first, "groceries for the room"),
  (@uid, @cat_transport,   60.00, @first, "rickshaw to campus"),
  (@uid, @cat_food,       130.00, DATE_SUB(CURDATE(), INTERVAL 1 DAY), "tehari + borhani"),
  (@uid, @cat_transport,  120.00, DATE_SUB(CURDATE(), INTERVAL 1 DAY), "CNG to Badda"),
  (@uid, @cat_books,      150.00, DATE_SUB(CURDATE(), INTERVAL 1 DAY), "photocopy, lab manual"),
  (@uid, @cat_fun,        350.00, DATE_SUB(CURDATE(), INTERVAL 1 DAY), "movie at Bashundhara City"),
  (@uid, @cat_food,        90.00, CURDATE(), "cha + singara"),
  (@uid, @cat_transport,   80.00, CURDATE(), "Pathao ride"),
  (@uid, @cat_other,      200.00, CURDATE(), "haircut");

SET @month = DATE_FORMAT(CURDATE(), "%Y-%m");
SET @prev  = DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH), "%Y-%m");

INSERT INTO `budgets` (`user_id`, `month_year`, `category_id`, `total_limit`) VALUES
  (@uid, @month, NULL, 16000.00),
  (@uid, @prev,  NULL, 16000.00);

INSERT INTO `budgets` (`user_id`, `month_year`, `category_id`, `category_limit`) VALUES
  (@uid, @month, @cat_food, 4500.00),
  (@uid, @month, @cat_transport, 2500.00),
  (@uid, @month, @cat_rent, 7000.00),
  (@uid, @month, @cat_mobile, 600.00),
  (@uid, @month, @cat_fun, 1000.00),
  (@uid, @month, @cat_books, 800.00);

INSERT INTO `savings_goals` (`user_id`, `title`, `target_amount`, `saved_amount`, `deadline`) VALUES
  (@uid, "Next trimester tuition", 45000.00, 18500.00, DATE_ADD(CURDATE(), INTERVAL 3 MONTH)),
  (@uid, "Second-hand laptop",     60000.00, 21000.00, DATE_ADD(CURDATE(), INTERVAL 7 MONTH)),
  (@uid, "Eid trip home",           6000.00,  6000.00, DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
  (@uid, "Emergency fund",         20000.00,  4500.00, NULL);
